backend:
  name: github
  repo: bada1951a/astro-paper
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "public/images/posts"
public_folder: "/images/posts"

collections:
  - name: "posts"
    label: "블로그 포스트"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "메타 제목", name: "meta_title", widget: "string", required: false}
      - {label: "설명", name: "description", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "대표 이미지", name: "image", widget: "image", required: false}
      - {label: "카테고리", name: "categories", widget: "list", default: ["Tech"]}
      - {label: "작성자", name: "author", widget: "string", default: "명원"}
      - {label: "임시저장 여부", name: "draft", widget: "boolean", default: false}
      - {label: "본문", name: "body", widget: "markdown"}
